# Generated by Django 3.0.6 on 2021-05-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OderDetail',
        ),
    ]
